[FS-22] - Create Price on Stripe
flatironsdevelopment/flatirons-saas pull request #18
Opened 2022-07-14 12:51 UTC by gleandroj

## Description
[FS-22] - Create Price on Stripe

## Tickets

[FS-22](https://flatirons.atlassian.net/browse/FS-22)

## Screenshots / Demos

2022-07-14 20:56 UTC, animista01 requested changes
does your changes require a swagger doc update? IDK

2022-07-14 20:56 UTC, animista01 commented on spec/flatirons/saas/services/stripe_service_spec.rb
> +          expect(price.id).to be
Lets put it as explicitly as we can 
`not_to be_nil`

2022-07-14 20:56 UTC, animista01 commented on spec/flatirons/saas/services/stripe_service_spec.rb
> +          expect(prices.length).to eq 2
use `#size`, `length` is more use to count letters in word for instance.

2022-07-15 13:24 UTC, gleandroj commented
> does your changes require a swagger doc update? IDK

It doesn’t

2022-07-15 13:59 UTC, animista01 approved these changes

2022-07-15 14:23 UTC, merged